name: Build master PDF from README

on:
  workflow_dispatch: {}
  push:
    paths:
      - "README.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests PyPDF2 reportlab pyyaml

      - name: Build master PDF from README
        run: |
          python scripts/build_from_readme.py

      - name: Commit master.pdf and updated README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: rebuild master.pdf & README page map"
            git push
          fi
